[package]
name = "pounce"
version = "0.1.0"
edition = "2024"
description = "🐾 Arrow-native ADBC driver for SQL Server — powered by tabby"
license = "MIT"
repository = "https://github.com/copycatdb/pounce"

[lib]
name = "pounce"
crate-type = ["cdylib"]

[features]
default = ["rustls", "chrono", "rust_decimal"]
rustls = ["tabby/rustls"]
chrono = ["tabby/chrono"]
rust_decimal = ["tabby/rust_decimal"]

[dependencies]
tabby = { git = "https://github.com/copycatdb/tabby.git", branch = "feat/initial-implementation" }
pyo3 = { version = "0.28", features = ["extension-module"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "sync", "macros"] }
tokio-util = { version = "0.7", features = ["compat"] }
once_cell = "1"
arrow = { version = "57", features = ["ffi"] }
chrono = { version = "0.4", default-features = false }
uuid = { version = "1", features = ["v4"] }
futures-util = { version = "0.3", default-features = false, features = ["io", "sink"] }
rust_decimal = "1"
